const errors = {
  UNKNOWN: 'UNKNOWN',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  LOGIN_REQUIRED: 'LOGIN_REQUIRED',
  NO_PERMISSION: 'NO_PERMISSION',
  USER_NOT_EXIST: 'USER_NOT_EXIST',
  NOT_ENOUGH_PERMISSION: 'NOT_ENOUGH_PERMISSION',
  WORKING_IN_PROCESS: 'WORKING_IN_PROCESS',
};

module.exports = errors;